'use client';

import { money, type Booking, type ExitNotice } from '../shared';

export function BookingsView({ bookings, notices, onAddBooking, onAddNotice, onAdvanceBooking, onCancelBooking, onAdvanceNotice }: { bookings: Booking[]; notices: ExitNotice[]; onAddBooking: () => void; onAddNotice: () => void; onAdvanceBooking: (id: number) => void; onCancelBooking: (id: number) => void; onAdvanceNotice: (id: number) => void }) {
  const live = bookings.filter((item) => !['checked-in', 'cancelled'].includes(item.status));
  const confirmed = bookings.filter((item) => item.status === 'confirmed');
  const tokens = bookings.filter((item) => item.status !== 'cancelled').reduce((sum, item) => sum + item.token, 0);
  const activeNotices = notices.filter((item) => item.status === 'open');
  const stageLabel: Record<Booking['status'], string> = { enquiry: 'Enquiry', visit: 'Visit planned', confirmed: 'Confirmed', 'checked-in': 'Checked in', cancelled: 'Cancelled' };
  const stages: { id: Extract<Booking['status'], 'enquiry' | 'visit' | 'confirmed'>; eyebrow: string; hint: string }[] = [
    { id: 'enquiry', eyebrow: 'New lead', hint: 'Start the conversation' },
    { id: 'visit', eyebrow: 'Visit planned', hint: 'Show the right bed' },
    { id: 'confirmed', eyebrow: 'Confirmed', hint: 'Prepare for move-in' },
  ];
  const completed = bookings.filter((item) => ['checked-in', 'cancelled'].includes(item.status));
  const bookingCard = (item: Booking) => <article key={item.id} className={`booking-card ${item.status === 'cancelled' ? 'inactive' : ''}`}>
    <header><span className="pipeline-avatar">{item.name.slice(0, 1)}</span><div><strong>{item.name}</strong><small>{item.source} · {item.phone}</small></div><span className={`booking-stage ${item.status}`}>{stageLabel[item.status]}</span></header>
    <dl><div><dt>Move-in</dt><dd>{new Date(`${item.moveIn}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</dd></div><div><dt>Preference</dt><dd>{item.sharing}</dd></div><div><dt>Rent</dt><dd>{money.format(item.quotedRent)}</dd></div><div><dt>Token</dt><dd>{item.token ? money.format(item.token) : 'Not paid'}</dd></div></dl>
    {!['checked-in', 'cancelled'].includes(item.status) && <footer><button className="record-button" onClick={() => onAdvanceBooking(item.id)}>{item.status === 'confirmed' ? 'Mark checked in' : item.status === 'visit' ? 'Confirm booking' : 'Plan visit'}</button><button className="cancel-link" onClick={() => onCancelBooking(item.id)}>Cancel</button></footer>}
  </article>;
  return <div className="view-stack"><section className="operations-summary"><article><span>{live.length}</span><p>Open prospects<small>Enquiry to confirmation</small></p></article><article><span>{confirmed.length}</span><p>Move-ins confirmed<small>Prepare beds and documents</small></p></article><article><span>{money.format(tokens)}</span><p>Booking tokens<small>Recorded, not processed online</small></p></article><article><span>{activeNotices.length}</span><p>Planned exits<small>Deposit checklist active</small></p></article></section>
    <section className="operations-grid"><article className="surface pipeline"><div className="surface-head pipeline-head"><div><p className="overline">BOOKING PIPELINE</p><h2>From first enquiry to move-in</h2><span>Each prospect has one clear next step.</span></div><button className="main-button" onClick={onAddBooking}>＋ New enquiry</button></div>{bookings.length ? <><div className="pipeline-board">{stages.map((stage) => { const items = bookings.filter((item) => item.status === stage.id); return <section className={`pipeline-column ${stage.id}`} key={stage.id}><header><div><span>{stage.eyebrow}</span><small>{stage.hint}</small></div><b>{items.length}</b></header><div>{items.length ? items.map(bookingCard) : <div className="stage-empty"><span>✓</span><p>No prospects here</p></div>}</div></section>; })}</div>{completed.length > 0 && <details className="pipeline-archive"><summary>Recent outcomes <span>{completed.length}</span></summary><div>{completed.map(bookingCard)}</div></details>}</> : <div className="empty pipeline-empty"><strong>Your pipeline is ready</strong><span>Add a prospect to track their visit, confirmation and move-in without losing the next step.</span><button className="quiet-button" onClick={onAddBooking}>Add first enquiry</button></div>}</article>
      <aside className="surface exit-board"><div className="surface-head"><div><p className="overline">EXIT CONTROL</p><h2>Notice & deposits</h2></div><button className="quiet-button" onClick={onAddNotice}>＋ Record notice</button></div>{notices.length ? <div className="notice-list">{notices.map((item) => <article key={item.id} className={item.status}><div><strong>{item.tenantName}</strong><small>Room {item.room} · vacates {new Date(`${item.vacateOn}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</small></div><span className={`deposit-state ${item.depositStatus}`}>{item.depositStatus === 'review' ? 'Inspect room' : item.depositStatus === 'ready' ? 'Refund ready' : 'Refunded'}</span>{item.status === 'open' && <button className="record-button" onClick={() => onAdvanceNotice(item.id)}>{item.depositStatus === 'review' ? 'Clear inspection' : 'Mark refunded'}</button>}</article>)}</div> : <div className="empty compact"><strong>No planned exits</strong><span>Record notice to protect availability and deposits.</span></div>}<footer className="operations-note"><i>i</i><p><strong>Never double-book a bed.</strong><span>Confirm the actual allotment from Property only after the resident checks in.</span></p></footer></aside>
    </section></div>;
}
