'use client';

import { type Tenant, type TenantDocument } from '../shared';

export function PaymentProofQueue({ tenants, documents, onPayment, onReview }: { tenants: Tenant[]; documents: TenantDocument[]; onPayment: (tenancyId: number) => void; onReview: (id: number, status: 'verified' | 'rejected') => void }) {
  const pending = documents.filter((document) => document.kind === 'payment_proof' && document.status === 'uploaded');
  if (!pending.length) return null;
  return <section className="surface payment-proof-queue"><div className="surface-head"><div><p className="overline">PAYMENT PROOF REVIEW</p><h2>{pending.length} receipt {pending.length === 1 ? 'awaits' : 'await'} review</h2></div><span className="document pending">Action needed</span></div><p className="queue-copy">Review the resident’s screenshot, then record the confirmed amount. Recording a receipt keeps the ledger accurate; approving the file preserves the proof.</p><div className="proof-list">{pending.map((document) => { const tenant = tenants.find((item) => item.id === document.tenancyId); return <article key={document.id}><div className="due-person"><span>{tenant?.name.slice(0, 1) ?? '₹'}</span><p><strong>{tenant?.name ?? 'Former resident'}</strong><small>Room {tenant?.room ?? '—'} · {document.originalName || document.label}</small></p></div><div className="row-actions"><a className="record-button" href={`/api/documents?id=${document.id}`}>View proof</a>{tenant && <button className="main-button" onClick={() => onPayment(tenant.id)}>Record payment</button>}<button className="record-button" onClick={() => onReview(document.id, 'verified')}>Mark reviewed</button></div></article>; })}</div></section>;
}

export function DocumentsView({ tenants, documents, onUpload, onReview, onDelete }: { tenants: Tenant[]; documents: TenantDocument[]; onUpload: () => void; onReview: (id: number, status: 'verified' | 'rejected') => void; onDelete: (id: number) => void }) {
  const verified = documents.filter((document) => document.status === 'verified').length;
  const review = documents.filter((document) => document.status === 'uploaded').length;
  return <div className="view-stack"><section className="document-hero"><div><p className="overline">RESIDENT DOCUMENTS</p><h2>Documents, consent and review in one owner workspace.</h2><p>Keep resident-provided proofs and agreements with a clear owner-review status. Mask Aadhaar copies before upload.</p></div><button className="main-button" onClick={onUpload}>⌑ Upload document</button></section><section className="document-summary"><article><span>{verified}</span><p>Files verified<small>Reviewed by the owner</small></p></article><article><span>{review}</span><p>Files to review<small>Uploaded with consent</small></p></article><article><span>{documents.length}</span><p>Total files<small>Owner account access</small></p></article></section><section className="surface document-list"><div className="surface-head"><div><p className="overline">DOCUMENT REGISTER</p><h2>Resident files</h2></div><button className="quiet-button" onClick={onUpload}>＋ Add file</button></div>{documents.length ? documents.map((document) => { const tenant = tenants.find((item) => item.id === document.tenancyId); return <article key={document.id}><div className="due-person"><span>{tenant?.name.slice(0, 1) ?? 'D'}</span><p><strong>{document.label}</strong><small>{tenant?.name ?? 'Former resident'} · {document.originalName || document.kind}</small></p></div><div><span className={`document ${document.status === 'verified' ? 'verified' : 'pending'}`}>{document.status.replace('_', ' ')}</span><small>{document.sizeBytes ? `${Math.ceil(document.sizeBytes / 1024)} KB` : 'Metadata only'}</small></div><div className="row-actions"><a className="record-button" href={`/api/documents?id=${document.id}`}>Download</a>{document.status === 'uploaded' && <><button className="record-button" onClick={() => onReview(document.id, 'verified')}>Verify</button><button className="icon-button danger" aria-label={`Reject ${document.label}`} onClick={() => onReview(document.id, 'rejected')}>×</button></>}<button className="icon-button danger" aria-label={`Delete ${document.label}`} title="Delete document" onClick={() => onDelete(document.id)}>⌫</button></div></article>; }) : <div className="empty"><strong>No files uploaded</strong><span>Add the first resident-provided proof or agreement. Consent is recorded with every upload.</span></div>}</section></div>;
}
