'use client';

import { type FormEvent } from 'react';
import { balanceFor, money, proratedRent, todayISO, type PropertyInfo, type ResidentInvite, type Tenant } from '../shared';

export function PropertyEditModal({ property, onClose, onSave }: { property: PropertyInfo; onClose: () => void; onSave: (name: string, address: string) => void }) {
  return <div className="modal-layer" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="Edit property" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Close" onClick={onClose}>×</button><p className="overline">PROPERTY DETAILS</p><h2>Edit property</h2><p className="modal-copy">The name shows across your workspace, receipts and reminders.</p><form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSave(String(data.get('name')), String(data.get('address'))); }}><label>Property name<input name="name" required defaultValue={property.name} /></label><label>Address or city<input name="address" defaultValue={property.address} /></label><button className="main-button full" type="submit">Save changes</button></form></section></div>;
}

export function ResidentInviteModal({ invite, onClose, onCopied }: { invite: ResidentInvite; onClose: () => void; onCopied: () => void }) {
  const portalUrl = `${window.location.origin}/tenant`;
  const firstName = invite.name.split(' ')[0] || invite.name;
  const message = `Hi ${firstName}, your RentWise resident portal for ${invite.propertyName} is ready. Sign in with ${invite.email} to view Room ${invite.room}, Bed ${invite.bed}, your rent, receipts and maintenance updates: ${portalUrl}`;
  const digits = (invite.phone ?? '').replace(/\D/g, '').slice(-10);
  const whatsapp = digits.length === 10 ? `https://wa.me/91${digits}?text=${encodeURIComponent(message)}` : null;
  async function copyInvite() {
    try { await navigator.clipboard.writeText(message); onCopied(); }
    catch { window.prompt('Copy this resident invitation', message); }
  }
  return <div className="modal-layer" onMouseDown={onClose}><section className="modal invite-modal" role="dialog" aria-modal="true" aria-label={`Invite ${invite.name} to RentWise`} onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Close invitation" onClick={onClose}>×</button><p className="overline">RESIDENT PORTAL READY</p><h2>Invite {invite.name}</h2><p className="modal-copy">Their portal opens only after they sign in with <b>{invite.email}</b>, the email saved on this tenancy.</p><div className="invite-summary"><span>Room {invite.room} · Bed {invite.bed}</span><small>{invite.propertyName}</small></div><div className="invite-message">{message}</div><div className="invite-actions">{whatsapp ? <a className="main-button" href={whatsapp} target="_blank" rel="noreferrer">Send on WhatsApp</a> : <button className="main-button" disabled>Add a mobile number for WhatsApp</button>}<button className="quiet-button" onClick={() => void copyInvite()}>Copy invitation</button></div><p className="invite-note">No account is created for the resident. They choose Google or email sign-in themselves.</p></section></div>;
}

export function AddTenantModal({ availableBeds, draftDate, draftRent, defaultSecurity, onDate, onRent, onClose, onSubmit }: { availableBeds: {room:string;bed:string}[]; draftDate:string; draftRent:number; defaultSecurity:number; onDate:(value:string)=>void; onRent:(value:number)=>void; onClose:()=>void; onSubmit:(event:FormEvent<HTMLFormElement>)=>void }) {
  return <div className="modal-layer" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="New allotment" onMouseDown={(event)=>event.stopPropagation()}><button className="modal-close" aria-label="Close" onClick={onClose}>×</button><p className="overline">NEW ALLOTMENT</p><h2>Move a tenant in</h2><p className="modal-copy">Create the resident record, assign a bed and calculate the exact first-month amount.</p><form onSubmit={onSubmit}><label>Full name<input name="name" required autoFocus placeholder="Tenant’s name" /></label><div className="form-row"><label>Phone number<input name="phone" inputMode="tel" autoComplete="tel" placeholder="Required for reminders" /></label><label>Email<input name="email" type="email" placeholder="Optional" /></label></div><div className="form-row"><label>Occupation<input name="occupation" placeholder="Optional" /></label><label>Hometown<input name="hometown" placeholder="Optional" /></label></div><div className="form-row"><label>Emergency contact<input name="emergencyName" placeholder="Optional" /></label><label>Emergency phone<input name="emergencyPhone" inputMode="tel" placeholder="Optional" /></label></div><div className="form-row"><label>Vacant bed<select name="bed" required>{availableBeds.map(({room,bed})=><option key={`${room}-${bed}`} value={`${room}-${bed}`}>Room {room} · Bed {bed}</option>)}</select></label><label>Allotment date<input name="allotment" type="date" value={draftDate} onChange={(event)=>onDate(event.target.value)} required /></label></div><div className="form-row"><label>Monthly rent<input name="rent" type="number" min="1" inputMode="numeric" value={draftRent} onChange={(event)=>onRent(Number(event.target.value))} required /></label><label>Security deposit<input name="security" type="number" min="0" inputMode="numeric" defaultValue={defaultSecurity} required /></label></div><div className="calculation"><span>First-month rent</span><strong>{money.format(proratedRent(draftRent,draftDate))}</strong><small>Calculated for the remaining days, including the move-in date.</small></div>{availableBeds.length === 0 && <p className="auth-error">No vacant beds right now — add another property or adjust the room plan.</p>}<button className="main-button full" type="submit" disabled={availableBeds.length === 0}>Create allotment</button></form></section></div>;
}

export function PaymentModal({ tenant, onClose, onSubmit }: { tenant: Tenant; onClose:()=>void; onSubmit:(event:FormEvent<HTMLFormElement>)=>void }) {
  return <div className="modal-layer" onMouseDown={onClose}><section className="modal payment-modal" role="dialog" aria-modal="true" aria-label="Record receipt" onMouseDown={(event)=>event.stopPropagation()}><button className="modal-close" aria-label="Close" onClick={onClose}>×</button><p className="overline">RECORD RECEIPT</p><h2>{tenant.name}</h2><p className="modal-copy">Room {tenant.room} · Bed {tenant.bed} · <b>{money.format(balanceFor(tenant))}</b> outstanding</p><form onSubmit={onSubmit}><label>Amount received<input name="amount" type="number" min="1" max={balanceFor(tenant)} defaultValue={balanceFor(tenant)} required /></label><div className="form-row"><label>Received on<input name="date" type="date" defaultValue={todayISO()} required /></label><label>Payment mode<select name="mode" defaultValue="UPI"><option>UPI</option><option>Cash</option><option>Bank transfer</option></select></label></div><label>Reference or note<input name="reference" placeholder="Optional UTR or note" /></label><label>Payment screenshot <small>optional, PDF/JPG/PNG/WebP up to 8 MB</small><input name="proof" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" /></label><button className="main-button full" type="submit">Save receipt</button></form></section></div>;
}

export function MaintenanceModal({ tenants, onClose, onSubmit }: { tenants: Tenant[]; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  return <div className="modal-layer" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="New maintenance request" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Close" onClick={onClose}>×</button><p className="overline">NEW REQUEST</p><h2>Log a repair</h2><p className="modal-copy">Capture the issue now, then move it from new to resolved as work progresses.</p><form onSubmit={onSubmit}><label>What needs attention?<input name="title" required autoFocus placeholder="e.g. Bathroom tap is leaking" /></label><div className="form-row"><label>Room<input name="room" required placeholder="12" /></label><label>Reported by<select name="tenant" defaultValue=""><option value="">Owner / staff</option>{tenants.map((tenant) => <option key={tenant.id} value={tenant.name}>{tenant.name} · Room {tenant.room}</option>)}</select></label></div><div className="form-row"><label>Category<select name="category" defaultValue="Plumbing"><option>Plumbing</option><option>Electrical</option><option>Carpentry</option><option>Housekeeping</option><option>Other</option></select></label><label>Priority<select name="priority" defaultValue="normal"><option value="urgent">Urgent</option><option value="normal">Normal</option><option value="low">Low</option></select></label></div><button className="main-button full" type="submit">Create request</button></form></section></div>;
}

export function BookingModal({ defaultRent, onClose, onSubmit }: { defaultRent: number; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const defaultMoveIn = new Date(); defaultMoveIn.setDate(defaultMoveIn.getDate() + 7);
  return <div className="modal-layer" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="New booking enquiry" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Close" onClick={onClose}>×</button><p className="overline">NEW ENQUIRY</p><h2>Add a prospective resident</h2><p className="modal-copy">Hold the conversation, expected move-in and token together before allotting a real bed.</p><form onSubmit={onSubmit}><label>Prospect name<input name="name" required autoFocus placeholder="Full name" /></label><div className="form-row"><label>Phone number<input name="phone" required inputMode="tel" pattern="[0-9 +()-]{10,16}" placeholder="10-digit mobile" /></label><label>Expected move-in<input name="moveIn" type="date" defaultValue={defaultMoveIn.toISOString().slice(0, 10)} required /></label></div><div className="form-row"><label>Preferred occupancy<select name="sharing"><option>Single room</option><option>Double sharing</option><option>Triple sharing</option><option>Four sharing</option><option>Dorm style</option></select></label><label>Lead source<select name="source"><option>WhatsApp</option><option>Walk-in</option><option>Referral</option><option>Google</option><option>Property portal</option><option>Other</option></select></label></div><div className="form-row"><label>Quoted monthly rent<input name="rent" type="number" min="0" defaultValue={defaultRent} required /></label><label>Token recorded<input name="token" type="number" min="0" defaultValue="0" /></label></div><p className="setup-note neutral"><i>i</i><span>Recording a token does not collect money. Use your approved payment provider for online payments.</span></p><button className="main-button full" type="submit">Add to pipeline</button></form></section></div>;
}

export function ExpenseModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  return <div className="modal-layer" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="Add expense" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Close" onClick={onClose}>×</button><p className="overline">NEW EXPENSE</p><h2>Record an operating cost</h2><p className="modal-copy">Keep property spending categorised so collections and profitability tell the same story.</p><form onSubmit={onSubmit}><div className="form-row"><label>Category<select name="category"><option>Utilities</option><option>Maintenance</option><option>Food</option><option>Salary</option><option>Supplies</option><option>Tax</option><option>Other</option></select></label><label>Amount<input name="amount" type="number" min="1" inputMode="numeric" required /></label></div><div className="form-row"><label>Spent on<input name="date" type="date" defaultValue={todayISO()} required /></label><label>Vendor<input name="vendor" placeholder="Optional" /></label></div><label>Description<input name="note" required placeholder="e.g. August electricity bill" /></label><button className="main-button full" type="submit">Save expense</button></form></section></div>;
}

export function ExitNoticeModal({ tenants, noticeDays, onClose, onSubmit }: { tenants: Tenant[]; noticeDays: number; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const vacate = new Date(); vacate.setDate(vacate.getDate() + noticeDays);
  return <div className="modal-layer" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="Record exit notice" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Close" onClick={onClose}>×</button><p className="overline">EXIT NOTICE</p><h2>Plan a resident checkout</h2><p className="modal-copy">Reserve the exit date, room inspection and deposit refund without losing the tenancy history.</p><form onSubmit={onSubmit}><label>Resident<select name="tenant" required disabled={!tenants.length}><option value="">Select a resident</option>{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.name} · Room {tenant.room}, Bed {tenant.bed}</option>)}</select></label><div className="form-row"><label>Notice received<input name="givenOn" type="date" defaultValue={todayISO()} required /></label><label>Planned vacate date<input name="vacateOn" type="date" defaultValue={vacate.toISOString().slice(0, 10)} required /></label></div>{!tenants.length && <p className="auth-error">Every active resident already has an open notice.</p>}<button className="main-button full" type="submit" disabled={!tenants.length}>Create exit checklist</button></form></section></div>;
}

export function DocumentUploadModal({ tenants, onClose, onSubmit }: { tenants: Tenant[]; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  return <div className="modal-layer" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="Upload resident document" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Close" onClick={onClose}>×</button><p className="overline">RESIDENT DOCUMENT</p><h2>Add a resident-provided file</h2><p className="modal-copy">PDF and images up to 8 MB. Mask the first eight Aadhaar digits before storing a copy.</p><form onSubmit={onSubmit}><label>Resident<select name="tenancyId" required><option value="">Select a resident</option>{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.name} · Room {tenant.room}</option>)}</select></label><div className="form-row"><label>Document type<select name="kind" defaultValue="identity"><option value="identity">Identity proof</option><option value="address">Address proof</option><option value="agreement">Rental agreement</option><option value="police_verification">Police verification</option><option value="other">Other</option></select></label><label>Label<input name="label" required placeholder="e.g. Masked Aadhaar" /></label></div><label>Choose file<input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" required /></label><label className="consent-check"><input name="consent" type="checkbox" required /><span>The resident provided this file and consented to its use for tenancy administration.</span></label><button className="main-button full" type="submit" disabled={!tenants.length}>Upload document</button></form></section></div>;
}
