'use client';

import { money, propertyInitials, type PropertyInfo, type RoomInventory, type Tenant } from '../shared';

export function PropertyView({ property, tenants, inventory, availableCount, onTenant, onAdd, onEdit, onNewProperty }: { property: PropertyInfo; tenants: Tenant[]; inventory: RoomInventory; availableCount: number; onTenant: (id: number) => void; onAdd: () => void; onEdit: () => void; onNewProperty: () => void }) {
  const totalBeds = inventory.reduce((sum, [, beds]) => sum + beds.length, 0);
  return <div className="view-stack"><section className="property-hero"><div><span className="property-badge">{propertyInitials(property.name)}</span><div><p className="overline">YOUR PROPERTY</p><h2>{property.name}</h2><p>{property.address}{property.city ? `, ${property.city}` : ''} · {property.audience ?? 'Co-living'} {property.type?.toLowerCase() ?? 'property'}</p></div></div><div className="property-facts"><div><span>{inventory.length}</span><small>Rooms</small></div><div><span>{totalBeds}</span><small>Beds</small></div><div><span>{tenants.length}</span><small>Residents</small></div><div><span>{totalBeds ? Math.round(tenants.length / totalBeds * 100) : 0}%</span><small>Occupied</small></div></div><div className="hero-actions"><button className="quiet-button" onClick={onEdit}>Edit</button><button className="quiet-button add-property-button" onClick={onNewProperty}>＋ New property</button><button className="main-button" onClick={onAdd}>＋ Allot bed</button></div></section>
    <section className="property-settings-strip"><div><span>Included amenities</span><p>{property.amenities?.length ? property.amenities.map((item) => <i key={item}>{item}</i>) : <i>Not configured</i>}</p></div><div><span>Collection defaults</span><strong>Due day {property.rentDueDay ?? 5} · {property.graceDays ?? 3}-day grace · {money.format(property.lateFee ?? 0)} late fee</strong></div><div><span>Operating profile</span><strong>{property.mealPlan ?? 'Meals not configured'} · {property.electricityPlan ?? 'Electricity not configured'} · {property.noticeDays ?? 30}-day notice</strong><p className="policy-mini"><i>{property.agreementRequired === false ? 'Agreement optional' : 'Agreement tracked'}</i><i>{property.verificationRequired === false ? 'Verification optional' : 'Verification tracked'}</i></p></div></section>
    <section className="surface"><div className="surface-head room-heading"><div><p className="overline">FLOOR PLAN · {property.floors ?? 1} {property.floors === 1 ? 'FLOOR' : 'FLOORS'}</p><h2>Room inventory</h2></div><div className="room-legend"><span><i className="legend-dot occupied" />Occupied</span><span><i className="legend-dot" />Vacant</span><span className="legend-count">{availableCount} ready to allot</span></div></div><div className="room-cards">{inventory.map(([room, beds]) => { const roomTenants = tenants.filter((tenant) => tenant.room === room); const monthly = roomTenants[0]?.rent ?? property.defaultRent ?? 3000; return <article className="room-detail" key={room}><div className="room-title"><span>ROOM</span><strong>{room}</strong><em>{roomTenants.length === beds.length ? 'Full' : `${beds.length - roomTenants.length} open`}</em></div><div className="bed-list">{beds.map((bed) => { const tenant = roomTenants.find((item) => item.bed === bed); return <button key={bed} className={tenant ? 'occupied' : ''} onClick={() => tenant ? onTenant(tenant.id) : onAdd()}><i>{bed}</i><span>{tenant ? tenant.name.split(' ')[0] : 'Vacant'}</span><b>{tenant ? 'View' : 'Allot'}</b></button>; })}</div><footer><span>{beds.length === 1 ? 'Single room' : `${beds.length} sharing`}</span><strong>{money.format(roomTenants[0]?.rent ?? monthly)} <small>/ bed</small></strong></footer></article>; })}</div></section></div>;
}
