'use client';

import { useState } from 'react';
import { balanceFor, formatPeriod, money, printReceipt, profileFor, waLink, type Receipt, type Tenant } from '../shared';

export function TenantDrawer({ tenant, propertyName = 'RentWise', history, onClose, onPayment, onInvite, onVacate, onUpdate, onVoidReceipt }: { tenant: Tenant; propertyName?: string; history?: Receipt[]; onClose: () => void; onPayment: () => void; onInvite: () => void; onVacate?: () => void; onUpdate?: (id: number, patch: { name?: string; phone?: string; email?: string; occupation?: string; hometown?: string; emergencyName?: string; emergencyPhone?: string; rent?: number; security?: number }) => void; onVoidReceipt?: (paymentId: number) => void }) {
  const [editing, setEditing] = useState(false);
  const profile = profileFor(tenant); const balance = balanceFor(tenant);
  const receipts = history ?? [];
  const whatsapp = waLink(tenant, propertyName, balance);
  return <div className="drawer-layer" onMouseDown={onClose}><aside className="drawer" role="dialog" aria-modal="true" aria-label={`Tenant profile: ${tenant.name}`} onMouseDown={(event)=>event.stopPropagation()}><header><button aria-label="Close profile" onClick={onClose}>×</button><div className="drawer-topline"><p className="overline">TENANT PROFILE</p>{onUpdate && <button className="link-button" onClick={() => setEditing((value) => !value)}>{editing ? 'Cancel' : '✎ Edit details'}</button>}</div><div className="drawer-person"><span>{tenant.name.split(' ').map((part)=>part[0]).join('').slice(0,2)}</span><div><h2>{tenant.name}</h2><p>Room {tenant.room} · Bed {tenant.bed}</p></div></div><div className="drawer-actions">{balance > 0 ? <button className="main-button" onClick={onPayment}>₹ Record payment</button> : <button className="main-button" disabled>✓ Balance clear</button>}{whatsapp ? <a className="quiet-button" href={whatsapp} target="_blank" rel="noreferrer">Message</a> : <button className="quiet-button" title="Add a phone number to enable WhatsApp">Message</button>}<button className="quiet-button" onClick={onInvite}>Invite to portal</button></div></header><div className="drawer-body">
    {editing && onUpdate ? (
      <form className="edit-grid" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); onUpdate(tenant.id, { name: String(data.get('name')), phone: String(data.get('phone')), email: String(data.get('email')), occupation: String(data.get('occupation')), hometown: String(data.get('hometown')), emergencyName: String(data.get('emergencyName')), emergencyPhone: String(data.get('emergencyPhone')), rent: Number(data.get('rent')), security: Number(data.get('security')) }); setEditing(false); }}>
        <label>Name<input name="name" required defaultValue={tenant.name} /></label>
        <label>Phone<input name="phone" defaultValue={tenant.phone ?? ''} placeholder="+91…" /></label>
        <label>Email<input name="email" type="email" defaultValue={tenant.email ?? ''} placeholder="Optional" /></label>
        <label>Occupation<input name="occupation" defaultValue={tenant.profession ?? ''} placeholder="Optional" /></label>
        <label>Hometown<input name="hometown" defaultValue={tenant.hometown ?? ''} placeholder="Optional" /></label>
        <label>Emergency contact<input name="emergencyName" defaultValue={tenant.emergencyName ?? ''} placeholder="Name" /></label>
        <label>Emergency phone<input name="emergencyPhone" defaultValue={tenant.emergencyPhone ?? ''} placeholder="Optional" /></label>
        <div className="form-row">
          <label>Monthly rent<input name="rent" type="number" min="0" defaultValue={tenant.rent} required /></label>
          <label>Security deposit<input name="security" type="number" min="0" defaultValue={tenant.security} required /></label>
        </div>
        <div className="drawer-actions"><button className="main-button" type="submit">Save changes</button><button className="quiet-button" type="button" onClick={() => setEditing(false)}>Cancel</button></div>
      </form>
    ) : (
      <section className="profile-grid"><div><span>Phone</span><strong>{tenant.phone ?? profile.phone}</strong></div><div><span>Occupation</span><strong>{profile.profession}</strong></div><div><span>Hometown</span><strong>{profile.hometown}</strong></div><div><span>Emergency</span><strong>{tenant.emergencyName ? `${tenant.emergencyName}${tenant.emergencyPhone ? ` · ${tenant.emergencyPhone}` : ''}` : 'Not recorded'}</strong></div><div><span>Allotted</span><strong>{new Date(`${tenant.allotment}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</strong></div></section>
    )}
    <section className="drawer-section"><div className="section-title"><h3>Rent standing</h3><span className={`pill ${balance?'part':'settled'}`}>{balance?'Balance due':'All clear'}</span></div><div className="rent-standing"><div><span>Monthly rent</span><strong>{money.format(tenant.rent)}</strong></div><div><span>Security deposit</span><strong>{money.format(tenant.security)}</strong></div><div className={balance?'highlight':''}><span>Total balance</span><strong>{balance?money.format(balance):'₹0'}</strong></div>{tenant.monthly && tenant.monthly.expected > 0 && (() => { const m = tenant.monthly!; return <div className={m.status === 'paid' ? '' : 'highlight'}><span>Rent · {formatPeriod(m.period)}</span><strong>{m.status === 'paid' ? 'Paid ✓' : m.status === 'partial' ? `${money.format(Math.max(0, m.expected - m.paid))} left` : money.format(m.expected)}</strong></div>; })()}</div></section>
    <section className="drawer-section"><div className="section-title"><h3>Documents</h3></div><p className="no-receipts">Document status is shown in the Documents workspace. Nothing is assumed or marked verified here.</p></section>
    <section className="drawer-section"><div className="section-title"><h3>Recent receipts</h3></div>{receipts.length ? <div className="receipts">{receipts.map((item,index)=><div key={`${item.id || index}`}><i>₹</i><p><strong>{money.format(item.amount)}</strong><span>{item.note} · {item.mode}{item.receiptNumber ? ` · ${item.receiptNumber}` : ''}</span></p>{item.hasProof && <a className="receipt-print" href={`/api/payments?proofId=${item.id}`} aria-label={`Download payment proof for ${money.format(item.amount)}`} title={item.proofName || 'Download payment proof'}>⌑</a>}<button className="receipt-print" aria-label={`Print receipt of ${money.format(item.amount)}`} title="Print receipt" onClick={() => printReceipt(tenant, propertyName, item, balance)}>⎙</button>{onVoidReceipt && item.id > 0 && <button className="receipt-void" aria-label={`Void receipt of ${money.format(item.amount)}`} title="Void receipt" onClick={() => onVoidReceipt(item.id)}>×</button>}<time>{item.date}</time></div>)}</div> : <p className="no-receipts">No receipts yet — record the first payment to start the ledger.</p>}</section>
    {onVacate && <section className="drawer-section"><div className="section-title"><h3>Tenancy</h3></div><div className="vacate-row"><p>Checked out? Closing the tenancy frees the bed and keeps every receipt on file.</p><button className="quiet-button danger" onClick={onVacate}>Vacate bed</button></div></section>}
  </div></aside></div>;
}
