'use client';

import { balanceFor, money, profileFor, type Tenant } from '../shared';

export function TenantsView({ tenants, totals, query, filter, onQuery, onFilter, onTenant, onPayment, rentDueDay = 5 }: { tenants: Tenant[]; totals: { active: number; verified: number; clear: number; rooms: number }; query: string; filter: 'all' | 'pending' | 'paid'; onQuery: (value: string) => void; onFilter: (value: 'all' | 'pending' | 'paid') => void; onTenant: (id: number) => void; onPayment: (id: number) => void; rentDueDay?: number }) {
  function exportCsv() {
    const quote = (value: string | number) => `"${String(value).replace(/"/g, '""')}"`;
    const header = 'Name,Room,Bed,Phone,Monthly rent,Security,First month rent,Received,Balance\n';
    const rows = tenants.map((tenant) => [tenant.name, tenant.room, tenant.bed, profileFor(tenant).phone, tenant.rent, tenant.security, tenant.firstMonthRent, tenant.received, balanceFor(tenant)].map(quote).join(','));
    const blob = new Blob([header + rows.join('\n')], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url; link.download = 'rentwise-tenants.csv'; link.click();
    URL.revokeObjectURL(url);
  }
  return <div className="view-stack"><section className="tenant-summary"><div><span>{totals.active}</span><p>Active tenants<small>Across {totals.rooms} occupied rooms</small></p></div><div><span>{totals.verified}</span><p>Documents verified<small>{totals.active - totals.verified} need review</small></p></div><div><span>{totals.clear}</span><p>Balances clear<small>{totals.active - totals.clear} need follow-up</small></p></div></section>
    <section className="surface directory"><div className="directory-tools"><label className="search-box">⌕<input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search name, room or phone" /></label><div className="segmented">{(['all','pending','paid'] as const).map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => onFilter(item)}>{item === 'all' ? 'All tenants' : item === 'pending' ? 'Payment due' : 'Paid'}</button>)}</div><button className="quiet-button" onClick={exportCsv}>⇩ Export</button></div>
      <div className="data-table"><table><thead><tr><th>Tenant</th><th>Room &amp; bed</th><th>Contact</th><th>Monthly rent</th><th>Documents</th><th>Balance</th><th>Status</th><th /></tr></thead><tbody>{tenants.map((tenant) => { const profile = profileFor(tenant); const balance = balanceFor(tenant); return <tr key={tenant.id} tabIndex={0} aria-label={`Open ${tenant.name}'s profile`} onClick={() => onTenant(tenant.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onTenant(tenant.id); } }}><td><div className="person"><span>{tenant.name.split(' ').map((part) => part[0]).join('').slice(0,2)}</span><p><strong>{tenant.name}</strong><small>Since {new Date(`${tenant.allotment}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</small></p></div></td><td><strong>Room {tenant.room}</strong><small className="subcell">Bed {tenant.bed}</small></td><td>{profile.phone}<small className="subcell">{profile.hometown}</small></td><td><strong>{money.format(tenant.rent)}</strong><small className="subcell">Due {rentDueDay}<sup>{['th','st','nd','rd'][rentDueDay % 10 > 3 || Math.floor(rentDueDay / 10) === 1 ? 0 : rentDueDay % 10] ?? 'th'}</sup> monthly</small></td><td><span className={`document ${profile.kyc}`}>{profile.kyc === 'verified' ? '✓ Verified' : '○ Pending'}</span></td><td className={balance ? 'due-text' : 'clear-text'}><strong>{balance ? money.format(balance) : 'Clear'}</strong></td><td><span className={`pill ${balance ? 'part' : 'settled'}`}>{balance ? 'Part paid' : 'Paid'}</span></td><td><button className="row-menu" onClick={(event) => { event.stopPropagation(); if (balance) onPayment(tenant.id); else onTenant(tenant.id); }}>{balance ? 'Record' : '•••'}</button></td></tr>; })}</tbody></table>{tenants.length === 0 && <div className="empty"><strong>{totals.active === 0 ? 'No tenants yet' : 'No matching tenants'}</strong><span>{totals.active === 0 ? 'Allot your first bed from the Property view.' : 'Try a different name, room or filter.'}</span></div>}</div>
    </section></div>;
}
